### ISSUE TITLE
Difficult to see Cursor Next to Highlighted Bracket Pair

### ISSUE THREAD

**Issue by VeryColdAir** [hellon8/VS2019-Dark-Npp#6]
I've been using this theme for a while now, and I generally love it. There's just one problem, and it occurs often enough that it's annoying: When using parentheses or brackets, and it can be hard to see where the cursor is at.

This is how the cursor looks in this theme: 
![hardtosee](https://github.com/hellon8/VS2019-Dark-Npp/assets/20274614/76239ebc-dba3-4c6f-a941-78cb59ec68bc)
Can you see it? It's located between the two parentheses at the end.

This is how the cursor shows up in Visual Studio 2019.
![image](https://github.com/hellon8/VS2019-Dark-Npp/assets/20274614/90a47fe3-f548-4c9d-ad44-2476ce2b1cc9)

Is there a way the contrast or colors for selected brackets and/or the cursor can be adjusted to improve visibility of the cursor when a bracket pair is highlighted?

**Comment by BigBauf** [comment]
Look under `<GlobalStyles>` for:
`<WidgetStyle name="Brace highlight style" styleID="34" fgColor="000000" bgColor="80ff80" fontName="" fontStyle="1" fontSize="" />` 
and change bgColor to a color you like

**Comment by VeryColdAir** [comment]
I settled on using `00698c` instead of `80ff80`. I'm able to easily see where the cursor is between two parentheses now.

![Untitled](https://github.com/hellon8/VS2019-Dark-Npp/assets/20274614/1faa0470-4dd9-4b04-846a-a9c48f2dafce)

**Comment by cbenard** [comment]
I made your change @VeryColdAir but I also changed the foreground color to white:
```xml
fgColor="FFFFFF" bgColor="00698C"
```

![image](https://github.com/hellon8/VS2019-Dark-Npp/assets/235748/612cba1a-82cb-48bb-a577-936bade25237)

@CennoxX @hellon8 can we re-open this? The default is very hard to see where the cursor is, like OP said, and it doesn't line up with VS. The changes above are closer to VS.

**Comment by cbenard** [comment]
Opened PR #7.

**Comment by CennoxX** [comment]
> I made your change @VeryColdAir but I also changed the foreground color to white:
> 
> ```
> fgColor="FFFFFF" bgColor="00698C"
> ```
> 
> ![image](https://user-images.githubusercontent.com/235748/274715250-612cba1a-82cb-48bb-a577-936bade25237.png)
> 
> @CennoxX @hellon8 can we re-open this? The default is very hard to see where the cursor is, like OP said, and it doesn't line up with VS. The changes above are closer to VS.

@cbenard I can't reopen, it's not my repo, I'm just a contributer.

**Comment by VeryColdAir** [comment]
> @CennoxX @hellon8 can we re-open this? 

Done.

**Comment by VeryColdAir** [comment]
> @CennoxX @hellon8 can we re-open this? The default is very hard to see where the cursor is, like OP said, and it doesn't line up with VS. The changes above are closer to VS.

Done.
